//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konamiman.NestorBugs.Data
{
    using Konamiman.NestorBugs.Data.Entities;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NestorBugsEntities : DbContext
    {
    
    	public NestorBugsEntities(string connectionString)
                : base(connectionString)
            {
            }
    
        public NestorBugsEntities()
            : base("name=NestorBugsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
    		//----- Modified for NestorBugs:
    	
    		//This exception is always thrown, even when creating the instance by using a connection string.
    		//Removing the exception seems to be safe.
    
            //throw new UnintentionalCodeFirstException();
        }
    
        public virtual IDbSet<User> Users { get; set; }
        public virtual IDbSet<Bug> Bugs { get; set; }
        public virtual IDbSet<Application> Applications { get; set; }
        public virtual IDbSet<BugVote> BugVotes { get; set; }
        public virtual IDbSet<BugComment> BugComments { get; set; }
        public virtual IDbSet<BugCommentVote> BugCommentVotes { get; set; }
        public virtual IDbSet<BugEditToken> BugEditTokens { get; set; }
    }
}
