//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konamiman.NestorBugs.Data.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using DataAnnotationsExtensions;

    public partial class Application
    {
        public Application()
        {
            this.Bugs = new HashSet<Bug>();
        }
    
        [Required]
        public int Id { get; set; }
    	
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
    	
    
        public virtual ICollection<Bug> Bugs { get; set; }
    	
    }
}
