//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konamiman.NestorBugs.Data.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using DataAnnotationsExtensions;

    public partial class Bug
    {
        public Bug()
        {
            this.Status = 0;
            this.Votes = new HashSet<BugVote>();
            this.Comments = new HashSet<BugComment>();
            this.BugEditToken = new HashSet<BugEditToken>();
        }
    
        [Required]
        [Display(Name="Id")]
        public int Id { get; set; }
    	
        [Required]
        [StringLength(200)]
        public string Title { get; set; }
    	
        [Required]
        [StringLength(10000)]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
    	
        [Required]
        [StringLength(2000)]
        [DataType(DataType.MultilineText)]
        public string Environment { get; set; }
    	
        [Required]
        public int UserId { get; set; }
    	
        public Nullable<int> ApplicationId { get; set; }
    	
        [StringLength(200)]
        [Display(Name="Application")]
        public string ApplicationName { get; set; }
    	
        [Required]
        [Display(Name="Created")]
        public System.DateTime CreationDate { get; set; }
    	
        [Required]
        public byte Status { get; set; }
    	
        [StringLength(20)]
        [Display(Name="Application Version")]
        public string ApplicationVersion { get; set; }
    	
        [Display(Name="Last edited")]
        public Nullable<System.DateTime> LastEditDate { get; set; }
    	
        [Required]
        [StringLength(200)]
        public string UrlTitle { get; set; }
    	
        [Required]
        public bool Locked { get; set; }
    	
        public Nullable<int> DuplicateBugId { get; set; }
    	
        public Nullable<int> LastEditUserId { get; set; }
    	
    
        public virtual Application Application { get; set; }
    	
        public virtual User User { get; set; }
    	
        public virtual ICollection<BugVote> Votes { get; set; }
    	
        public virtual ICollection<BugComment> Comments { get; set; }
    	
        public virtual ICollection<BugEditToken> BugEditToken { get; set; }
    	
    }
}
