//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konamiman.NestorBugs.Data.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using DataAnnotationsExtensions;

    public partial class BugEditToken
    {
        [Required]
        public int Id { get; set; }
    	
        [Required]
        public int UserId { get; set; }
    	
        [Required]
        public int BugId { get; set; }
    	
        [Required]
        [StringLength(32)]
        public string Token { get; set; }
    	
    
        public virtual Bug Bug { get; set; }
    	
    }
}
