//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konamiman.NestorBugs.Data.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using DataAnnotationsExtensions;

    public partial class User
    {
        public User()
        {
            this.Bugs = new HashSet<Bug>();
        }
    
        [Required]
        public int Id { get; set; }
    	
        [Required]
        [StringLength(30)]
        [Display(Name="Display name")]
        public string DisplayName { get; set; }
    	
        [Required]
        [StringLength(1000)]
        [Display(Name="OpenId identifier")]
        public string UserName { get; set; }
    	
        [StringLength(200)]
        [Email]
        [Display(Name="Email address")]
        public string Email { get; set; }
    	
        [StringLength(1000)]
        [Url]
        [Display(Name="Web page URL")]
        public string Url { get; set; }
    	
        [Required]
        [Display(Name="Member since")]
        public System.DateTime JoinedDate { get; set; }
    	
    
        public virtual ICollection<Bug> Bugs { get; set; }
    	
    }
}
